version: "3.8"

services:
  web:
    image: mywebsite
    build: .
    links:
      - db
    volumes:
      - ./src:/var/www/html
    ports:
      - 8999:80
  db:
    image: mariadb:latest
    volumes: 
    - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: db.env
    environment: 
      NODE_ENV: development

volumes:
  mariadb: