version: '3.8'

services:
  php-web:
    image: web-form
    build:
      context: .
    ports: 
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/30-custom.ini
    # environment:
    #   DATABASE_URL: webdb://admin@mariadb/db1
    #     - ALLOW_OVERRIDE=true
    links:
      - maria-db

  maria-db:
    image: mariadb:latest
    ports:
    - 3306:3306
    volumes:
    - mariadb:/var/lib/mysql
    env_file: db.env
    environment:
      NODE_ENV: development

volumes:
  mariadb:

